This is makeindex, version 2.15 [TeX Live 2021/W32TeX] (kpathsea + Thai support).
Scanning style file ./thesis.ist.............................done (29 attributes redefined, 0 ignored).
Scanning input file thesis.acn....done (451 entries accepted, 0 rejected).
Sorting entries......done (4410 comparisons).
Generating output file thesis.acr....done (175 lines written, 0 warnings).
Output written in thesis.acr.
Transcript written in thesis.alg.
